version: '3'

services:
  robot:
    build: robot
    #command: sh
    command: sh -c 'sleep 30 && python /robot/run.py --outputdir /results'
    environment:
      BROWSER: HeadlessChrome
      ENDPOINT: ${ENDPOINT}
    volumes:
      - ./robot:/robot:rw
      - ./results/robot:/results:rw
    depends_on:
      - dev
      - backend
